---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: my_ubuntu
provisioner:
  name: ansible
  inventory:
    links:
      hosts: /home/comp/ansible/00-molecule/inventory.yml
verifier:
  name: ansible
